name: Проверка shell-скрипта

on:
  push:
  pull_request:

jobs:
  proverka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Проверить синтаксис install.sh
        run: sh -n install.sh
